import { useState } from "react";
import { ArrowRight, Check, LogIn, Menu, ShieldCheck, X } from "lucide-react";

const text = {
  es: {
    locale:"English", nav:["Ecosistema","Producto","Principios","Acceso clientes"], contact:"Contacto", access:"Ingresar a Own Terra", eyebrow:"Con base en México · Operamos en México y EE. UU.",
    title:"El sistema operativo para", accent:"empresas inmobiliarias.", intro:"Own Terra centraliza lotificación, propiedades, CRM, contratos, cobranza y finanzas de tu operación inmobiliaria en una sola plataforma — hecha para operaciones reales en México y Estados Unidos.", primary:"Conoce el ecosistema", secondary:"Hablemos", built:"Diseñado para", sectors:["Lotificadoras","Fraccionamientos","Desarrolladoras","Inmobiliarias"],
    serviceTag:"El ecosistema", serviceTitle:"Un ecosistema, no una suite de parches.", serviceNote:"Cada aplicación vive en su propio espacio, conectada a la misma fuente de datos.", statusOn:"Activo", statusSoon:"Próximamente",
    services:[["OwnTerra Lands","Lotificación, trazo y subdivisión de terrenos con planos topográficos y control de preventas.",["Planos DWG/PDF","Compraventa","Enganches"],"Explorar Lands"],["OwnTerra Properties","Administración de propietarios, inmuebles y unidades rentables desde un solo espacio operativo.",["Propietarios","Propiedades","Unidades"],"Explorar Properties"],["OwnTerra Construction","Seguimiento de obra para desarrollos habitacionales: avances, bitácora y proveedores.",["Bitácora de obra","Avances","Proveedores"],"Ver Construction"]],
    workTag:"Cómo funciona",workTitle:"Toda tu operación, en un solo sistema.",workBody:"Own Terra conecta inventario de lotes y propiedades, CRM, contratos, cobranza y finanzas en una plataforma pensada para operaciones inmobiliarias reales.", bullets:["Lotes, propiedades y desarrollos en un solo sistema","Pipeline comercial desde el prospecto hasta el contrato","Pagos, saldos y flujo de caja por proyecto","Experiencias web y móvil para equipos en campo"], build:"Agenda una demo", ready:"PRODUCTO LISTO",
    cards:[["Ventas e inventario","Lotes, disponibilidad, clientes y seguimiento centralizados."],["Contratos y cobranza","Una ruta operativa clara desde la firma hasta el pago."],["Un ecosistema conectado","Web, móvil y automatización con una sola fuente de verdad."]], cardTags:["LOTES","CONTRATOS","ECOSISTEMA"],
    why:"Por qué Own Terra", whyTitle:"Seguridad y velocidad — para tu operación.", principles:[["01","Seguridad primero","Infraestructura segura, control de acceso por rol y respaldo continuo de tu información."],["02","Automatización útil","Cálculo de comisiones, recordatorios de cobranza y reportes que se generan solos."],["03","Hecho para crecer","Se adapta a una lotificadora, un fraccionamiento o varias organizaciones a la vez."],["04","Soporte cercano","Un equipo que conoce tu operación y responde cuando lo necesitas."]],
    discoverTag:"Explora el ecosistema",discoverTitle:"Conoce todo lo que Own Terra puede hacer por tu operación.",discoverBody:"Descubre sus soluciones para inventario, ventas, clientes, contratos, cobranza y finanzas.",discoverCta:"Entrar al ecosistema",accessTag:"Portal de clientes",accessTitle:"Tu operación inmobiliaria, en un solo lugar.",accessBody:"Ingresa a tu cuenta para consultar clientes, inventario, contratos, cobranza y documentos.",accessSecure:"Acceso seguro y exclusivo para organizaciones registradas",accessHelp:"¿Necesitas ayuda para entrar?",contactTitle:"Hablemos de tu operación.",contactBody:"Cuéntanos de tu equipo y tu operación inmobiliaria — te mostramos cómo Own Terra puede ayudarte. Respondemos en menos de un día hábil.",labels:["Nombre","Empresa","Correo","Mensaje"],send:"Enviar mensaje",sent:"Mensaje recibido. Nos pondremos en contacto pronto.",emailCta:"Escríbenos",footer:"Ecosistema operativo para empresas inmobiliarias · México y Estados Unidos"
  },
  en: {
    locale:"Español", nav:["Ecosystem","Product","Principles","Client access"], contact:"Contact", access:"Open Own Terra", eyebrow:"Based in Mexico · Operating in Mexico & the US", title:"The operating system for", accent:"real-estate companies.", intro:"Own Terra centralizes land sales, properties, CRM, contracts, collections and finance for your real-estate operation in one platform — built for real operations in Mexico and the United States.", primary:"Explore the ecosystem", secondary:"Talk to us", built:"Built for", sectors:["Land developers","Subdivisions","Homebuilders","Real-estate firms"],
    serviceTag:"The ecosystem",serviceTitle:"One ecosystem, not a patchwork of tools.",serviceNote:"Every app lives in its own space, connected to the same source of data.",statusOn:"Active",statusSoon:"Coming soon",services:[["OwnTerra Lands","Land subdivision, surveying and lot tracking with topographic plans and pre-sale control.",["DWG/PDF plans","Sales","Down payments"],"Explore Lands"],["OwnTerra Properties","Manage owners, properties and rental units from one operational space.",["Owners","Properties","Units"],"Explore Properties"],["OwnTerra Construction","Build tracking for housing developments: progress, daily log and vendors.",["Daily log","Progress","Vendors"],"View Construction"]],
    workTag:"How it works",workTitle:"Your whole operation, one system.",workBody:"Own Terra connects lot and property inventory, CRM, contracts, collections and finance in a platform built for real real-estate operations.",bullets:["Lots, properties and developments in one system","Commercial pipeline from lead to signed contract","Payments, balances and cash flow by project","Web and mobile experiences for teams in the field"],build:"Book a demo",ready:"PRODUCT READY",cards:[["Sales & inventory","Centralized lots, availability, clients and follow-up."],["Contracts & collections","A clear operational trail from signature to payment."],["One connected ecosystem","Web, mobile and automation sharing one source of truth."]],cardTags:["LOTS","CONTRACTS","ECOSYSTEM"],
    why:"Why Own Terra",whyTitle:"Security and speed — for your operation.",principles:[["01","Security first","Secure infrastructure, role-based access and continuous backup of your data."],["02","Useful automation","Commission calculations, collection reminders and reports that build themselves."],["03","Built to grow","Fits one land developer, one subdivision, or several organizations at once."],["04","Close support","A team that knows your operation and answers when you need it."]],discoverTag:"Explore the ecosystem",discoverTitle:"Discover everything Own Terra can do for your operation.",discoverBody:"Explore solutions for inventory, sales, clients, contracts, collections and finance.",discoverCta:"Enter the ecosystem",accessTag:"Client portal",accessTitle:"Your real-estate operation, all in one place.",accessBody:"Sign in to manage clients, inventory, contracts, collections, and documents.",accessSecure:"Secure access for registered organizations only",accessHelp:"Need help signing in?",contactTitle:"Let’s talk about your operation.",contactBody:"Tell us about your team and your real-estate operation — we’ll show you how Own Terra can help. We respond within one business day.",labels:["Name","Company","Email","Message"],send:"Send message",sent:"Message received. We’ll be in touch shortly.",emailCta:"Email us",footer:"Operating ecosystem for real-estate companies · Mexico & United States"
  }
};
const hubApps=[["Lands","/icons/app-lands.png"],["Properties","/icons/app-properties.png"],["Construction","/icons/app-construction.png"]];
const ecosystemMeta=[
  {icon:"/icons/app-lands.png",accent:"#4fe8cd",status:"on",handle:"terra.lands",landing:"/lands.html",video:"/videos/own-terra-demo.mp4",poster:"/videos/own-terra-demo-poster.jpg"},
  {icon:"/icons/app-properties.png",accent:"#7c9dff",status:"on",handle:"terra.properties",landing:"/properties.html",video:"/videos/ownterra_properties.mp4",poster:"/videos/ownterra-properties-poster.jpg"},
  {icon:"/icons/app-construction.png",accent:"#e8bd3f",status:"on",handle:"terra.construct",landing:"/construction.html",video:"/videos/own-terra-Constructions.mp4",poster:"/videos/own-terra-construction-poster.jpg"},
];
const Brand=()=> <a className="brand" href="#top"><span className="mark"><i/></span><b>OWN TERRA</b></a>;
const HubMiniGrid=({asset})=> <div className="hubMiniGrid">{hubApps.map(([name,icon])=><div key={name} className="hubMiniCard"><img src={asset(icon)} alt={name}/><span>{name}</span></div>)}</div>;

export default function App(){
  const [lang,setLang]=useState("es"),[menu,setMenu]=useState(false); const t=text[lang];
  const asset=(path)=>`${import.meta.env.BASE_URL}${path.replace(/^\//,"")}`;
  function submit(e){e.preventDefault();const data=new FormData(e.currentTarget);const subject=encodeURIComponent(`Contacto web · ${data.get("company")||data.get("name")}`);const body=encodeURIComponent(`${data.get("message")}\n\n${data.get("name")}\n${data.get("company")||""}\n${data.get("email")}`);window.location.href=`mailto:safeports.contacto@gmail.com?subject=${subject}&body=${body}`}
  return <div className="site">
    <header className="nav"><Brand/><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menú" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button><nav className={menu?"links open":"links"}>{t.nav.map((x,i)=><a key={x} href={["#services","#work","#principles","#client-access"][i]} onClick={()=>setMenu(false)}>{x}</a>)}<button onClick={()=>setLang(lang==="es"?"en":"es")}>{t.locale}</button><a className="navCta" href="#contact">{t.contact}</a></nav></header>
    <main id="top">
      <section className="hero shell"><div className="eyebrow"><span/>{t.eyebrow}</div><h1>{t.title}<br/><em>{t.accent}</em></h1><p>{t.intro}</p><div className="actions"><a className="button primary" href="#work">{t.primary}<ArrowRight/></a><a className="button ghost" href="#contact">{t.secondary}</a></div><div className="trust"><small>{t.built}</small>{t.sectors.map(x=><span key={x}>{x}</span>)}</div></section>
      <section className="section shell" id="services"><header><small>{t.serviceTag}</small><h2>{t.serviceTitle}</h2><p>{t.serviceNote}</p></header><div className="ecoList">{t.services.map(([name,desc,tags,cta],i)=>{const m=ecosystemMeta[i];const href=m.landing;return <article key={name} className="ecoCard" style={{"--eco":m.accent}}><div className="ecoText"><div className="ecoTop"><a className="ecoIcon" href={href} aria-label={`${cta}: ${name}`}><img src={asset(m.icon)} alt=""/></a><span className="ecoStatus">{t.statusOn}</span></div><h3>{name}</h3><p className="ecoHandle">{m.handle}</p><p className="ecoDesc">{desc}</p><div className="ecoTags">{tags.map(tg=><span key={tg}>{tg}</span>)}</div><a className="ecoCta" href={href}>{cta}<ArrowRight/></a></div><a className="ecoMedia" href={href} aria-label={`${cta}: ${name}`}>{m.video?<video className="ecoVideo" autoPlay muted loop playsInline preload="metadata" poster={asset(m.poster)} aria-hidden="true"><source src={asset(m.video)} type="video/mp4"/></video>:<div className="ecoMediaIcon"><img src={asset(m.icon)} alt=""/></div>}</a></article>})}</div></section>
      <section className="section shell work" id="work"><div className="workCopy"><small>{t.workTag}</small><h2>{t.workTitle}</h2><p>{t.workBody}</p><ul>{t.bullets.map(x=><li key={x}><Check/>{x}</li>)}</ul><a className="button outline" href="#contact">{t.build}<ArrowRight/></a></div><a className="window hubWindow" href="/hub.html"><div className="bar"><i/><i/><i/><span>own-terra.com/hub</span></div><div className="product"><div><b>OWN TERRA · Hub</b><span>{t.ready}</span></div><HubMiniGrid asset={asset}/><div className="hubMiniFoot">{t.discoverCta}<ArrowRight/></div></div></a><div className="caseGrid">{t.cards.map(([a,b],i)=><article key={a}><span>{t.cardTags[i]}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
      <section className="section shell ownTerraGateway"><div><small>{t.discoverTag}</small><h2>{t.discoverTitle}</h2><p>{t.discoverBody}</p></div><a className="button primary" href="/hub.html">{t.discoverCta}<ArrowRight/></a></section>
      <section className="section shell clientAccess" id="client-access"><div className="accessVisual"><div className="accessShield"><ShieldCheck/></div><span>OWN TERRA · ACCESO SEGURO</span><HubMiniGrid asset={asset}/></div><div className="accessCopy"><small>{t.accessTag}</small><h2>{t.accessTitle}</h2><p>{t.accessBody}</p><div className="secureNote"><ShieldCheck/>{t.accessSecure}</div><a className="button primary accessButton" href="/hub.html">{t.access}<LogIn/></a><a className="accessHelp" href="mailto:safeports.contacto@gmail.com">{t.accessHelp} <ArrowRight/></a></div></section>
      <section className="section shell" id="principles"><div className="principle"><header><small>{t.why}</small><h2>{t.whyTitle}</h2></header><div className="principleGrid">{t.principles.map(([n,a,b])=><article key={n}><span>{n}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
      <section className="section shell contact" id="contact"><div><small>{t.contact}</small><h2>{t.contactTitle}</h2><p>{t.contactBody}</p><a href="mailto:safeports.contacto@gmail.com">{t.emailCta}</a><span>México · United States</span></div><form onSubmit={submit}><div className="fieldRow"><label>{t.labels[0]}<input required name="name" autoComplete="name"/></label><label>{t.labels[1]}<input name="company" autoComplete="organization"/></label></div><label>{t.labels[2]}<input required type="email" name="email" autoComplete="email"/></label><label>{t.labels[3]}<textarea required name="message" rows="5"/></label><button className="button primary">{t.send}<ArrowRight/></button></form></section>
    </main><footer><Brand/><span>© 2026</span><p>{t.footer}</p></footer>
  </div>
}
