import { useState } from "react";
import { ArrowRight, Check, Code2, HeartPulse, Building2, Megaphone, HardHat, LogIn, Menu, ShieldCheck, X } from "lucide-react";

const text = {
  es: {
    locale:"English", nav:["Servicios","Proyectos","Principios","Acceso clientes"], contact:"Contacto", access:"Ingresar a Own Terra", eyebrow:"Con base en México · Trabajamos en México y EE. UU.",
    title:"Software a la medida para un", accent:"mundo que no espera.", intro:"Safe Ports desarrolla productos seguros e inteligentes para distintas industrias. Own Terra—nuestra plataforma operativa inmobiliaria—es el mejor ejemplo de cómo convertimos operaciones complejas en software sencillo.", primary:"Conoce nuestro trabajo", secondary:"Hablemos", built:"Diseñado para", sectors:["Bienes raíces","Salud","Construcción","Retail"],
    serviceTag:"Lo que hacemos", serviceTitle:"Software a la medida, industria por industria.", serviceNote:"Desde el descubrimiento hasta producción y todo lo que sigue.",
    services:[["Desarrollo de software","Productos full-stack diseñados para escalar, desde la primera línea de código hasta producción."],["Sistemas de salud","Herramientas seguras diseñadas alrededor de los flujos clínicos y las personas que las usan."],["Tecnología inmobiliaria","Ventas, CRM, cobranza y operación de proyectos conectados en un ecosistema."],["Sistemas de marketing","Automatización y publicación conectadas directamente con la operación."],["Tecnología para construcción","Herramientas para seguimiento de obra, proveedores y entregas."]],
    workTag:"Producto insignia",workTitle:"Own Terra: un ecosistema para empresas inmobiliarias.",workBody:"Own Terra integra venta de lotes, desarrollos de vivienda, CRM, contratos, cobranza, construcción y marketing en una plataforma creada para operaciones reales en México y Estados Unidos.", bullets:["Lotes, propiedades y desarrollos en un solo sistema","Pipeline comercial desde el prospecto hasta el contrato","Pagos, saldos y flujo de caja por proyecto","Experiencias web y móvil para equipos en campo"], build:"Construye con nosotros", overview:"Resumen operativo",ready:"PRODUCTO LISTO",
    cards:[["Ventas e inventario","Lotes, disponibilidad, clientes y seguimiento centralizados."],["Contratos y cobranza","Una ruta operativa clara desde la firma hasta el pago."],["Un ecosistema conectado","Web, móvil y automatización con una sola fuente de verdad."]],
    why:"Por qué Safe Ports", whyTitle:"Seguridad y velocidad—juntas.", principles:[["01","Seguridad primero","Infraestructura segura e ingeniería rigurosa desde el inicio."],["02","Inteligencia útil","Automatizamos lo repetitivo para enfocarse en decisiones."],["03","Hecho para evolucionar","Diseñamos para la siguiente etapa del negocio."],["04","Colaboración cercana","Entendemos, entregamos por etapas y respondemos después del lanzamiento."]],
    demoTag:"Own Terra en acción",demoTitle:"Una operación completa, sin fricción.",demoBody:"Descubre cómo Own Terra convierte inventario, ventas, contratos y cobranza en una experiencia clara para todo el equipo.",demoHint:"Activa el sonido para escuchar la presentación",discoverTag:"Explora el ecosistema",discoverTitle:"Conoce todo lo que Own Terra puede hacer por tu operación.",discoverBody:"Descubre sus soluciones para inventario, ventas, clientes, contratos, cobranza, propiedades, construcción y marketing.",discoverCta:"Ir a la página de Own Terra",accessTag:"Portal de clientes",accessTitle:"Tu operación inmobiliaria, en un solo lugar.",accessBody:"Si tu organización ya utiliza Own Terra, ingresa desde este portal seguro para consultar clientes, inventario, contratos, cobranza y documentos.",accessSecure:"Acceso seguro y exclusivo para organizaciones registradas",accessPending:"Enlace de acceso pendiente",accessHelp:"¿Necesitas ayuda para entrar?",contactTitle:"Construyamos algo seguro.",contactBody:"Cuéntanos qué quieres construir o dónde se está atorando tu operación. Respondemos en menos de un día hábil.",labels:["Nombre","Empresa","Correo","Mensaje"],send:"Enviar mensaje",sent:"Mensaje recibido. Nos pondremos en contacto pronto.",footer:"Software a la medida · México y Estados Unidos"
  },
  en: {
    locale:"Español", nav:["Services","Work","Principles","Client access"], contact:"Contact", access:"Open Own Terra", eyebrow:"Based in Mexico · Serving Mexico & the US", title:"Custom software for a", accent:"world that won’t wait.", intro:"Safe Ports builds secure, intelligent products across industries. Own Terra—our real-estate operating platform—is the clearest example of how we turn complex operations into simple software.", primary:"Explore our work", secondary:"Talk to us", built:"Built for", sectors:["Real estate","Healthcare","Construction","Retail"],
    serviceTag:"What we do",serviceTitle:"Custom software, industry by industry.",serviceNote:"From discovery to production—and the evolution that follows.",services:[["Software development","Full-stack products engineered for scale, from the first line of code to production."],["Healthcare systems","Secure tools designed around clinical workflows and the people who use them."],["Property technology","Sales, CRM, collections and projects connected in one ecosystem."],["Marketing systems","Automation and publishing connected directly to operations."],["Construction tech","Digital tools for build tracking, vendors and delivery."]],
    workTag:"Flagship product",workTitle:"Own Terra: one ecosystem for real-estate companies.",workBody:"Own Terra brings land sales, housing developments, CRM, contracts, collections, construction and marketing together in one platform—built for real operations in Mexico and the United States.",bullets:["Lots, properties and developments in one system","Commercial pipeline from lead to signed contract","Payments, balances and cash flow by project","Web and mobile experiences for teams in the field"],build:"Build with us",overview:"Operations overview",ready:"PRODUCT READY",cards:[["Sales & inventory","Centralized lots, availability, clients and follow-up."],["Contracts & collections","A clear operational trail from signature to payment."],["One connected ecosystem","Web, mobile and automation sharing one source of truth."]],
    why:"Why Safe Ports",whyTitle:"Security and speed—together.",principles:[["01","Security first","Secure infrastructure and rigorous engineering from day one."],["02","Useful intelligence","We automate busywork so teams can focus on decisions."],["03","Built to evolve","Products are designed for the business’s next stage."],["04","Close partnership","We learn, ship in stages and stay accountable after launch."]],demoTag:"Own Terra in action",demoTitle:"A complete operation, without friction.",demoBody:"See how Own Terra turns inventory, sales, contracts, and collections into one clear experience for the entire team.",demoHint:"Turn on sound to hear the presentation",discoverTag:"Explore the ecosystem",discoverTitle:"Discover everything Own Terra can do for your operation.",discoverBody:"Explore solutions for inventory, sales, clients, contracts, collections, properties, construction, and marketing.",discoverCta:"Visit the Own Terra website",accessTag:"Client portal",accessTitle:"Your real-estate operation, all in one place.",accessBody:"If your organization already uses Own Terra, sign in through this secure portal to manage clients, inventory, contracts, collections, and documents.",accessSecure:"Secure access for registered organizations only",accessPending:"Access link pending",accessHelp:"Need help signing in?",contactTitle:"Let’s build something secure.",contactBody:"Tell us what you’re building or where your operation is getting stuck. We’ll respond within one business day.",labels:["Name","Company","Email","Message"],send:"Send message",sent:"Message received. We’ll be in touch shortly.",footer:"Custom software · Mexico & United States"
  }
};
const icons=[Code2,HeartPulse,Building2,Megaphone,HardHat];
const Brand=()=> <a className="brand" href="#top"><span className="mark"><i/></span><b>SAFE PORTS</b></a>;

export default function App(){
  const [lang,setLang]=useState("es"),[menu,setMenu]=useState(false); const t=text[lang];
  const ownTerraUrl=import.meta.env.VITE_OWN_TERRA_URL?.trim();
  const asset=(path)=>`${import.meta.env.BASE_URL}${path.replace(/^\//,"")}`;
  function submit(e){e.preventDefault();const data=new FormData(e.currentTarget);const subject=encodeURIComponent(`Contacto web · ${data.get("company")||data.get("name")}`);const body=encodeURIComponent(`${data.get("message")}\n\n${data.get("name")}\n${data.get("company")||""}\n${data.get("email")}`);window.location.href=`mailto:safeports.contacto@gmail.com?subject=${subject}&body=${body}`}
  return <div className="site">
    <header className="nav"><Brand/><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menú" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button><nav className={menu?"links open":"links"}>{t.nav.map((x,i)=><a key={x} href={["#services","#work","#principles","#client-access"][i]} onClick={()=>setMenu(false)}>{x}</a>)}<button onClick={()=>setLang(lang==="es"?"en":"es")}>{t.locale}</button><a className="navCta" href="#contact">{t.contact}</a></nav></header>
    <main id="top">
      <section className="hero shell"><div className="eyebrow"><span/>{t.eyebrow}</div><h1>{t.title}<br/><em>{t.accent}</em></h1><p>{t.intro}</p><div className="actions"><a className="button primary" href="#work">{t.primary}<ArrowRight/></a><a className="button ghost" href="#contact">{t.secondary}</a></div><div className="trust"><small>{t.built}</small>{t.sectors.map(x=><span key={x}>{x}</span>)}</div></section>
      <section className="section shell" id="services"><header><small>{t.serviceTag}</small><h2>{t.serviceTitle}</h2><p>{t.serviceNote}</p></header><div className="serviceGrid">{t.services.map(([a,b],i)=>{const Icon=icons[i];return <article key={a}><div className="icon"><Icon/></div><h3>{a}</h3><p>{b}</p></article>})}</div></section>
      <section className="section shell work" id="work"><div className="workCopy"><small>{t.workTag}</small><h2>{t.workTitle}</h2><p>{t.workBody}</p><ul>{t.bullets.map(x=><li key={x}><Check/>{x}</li>)}</ul><a className="button outline" href="#contact">{t.build}<ArrowRight/></a></div><div className="window"><div className="bar"><i/><i/><i/><span>ownterra.mx</span></div><div className="product"><div><b>OWN TERRA · {t.overview}</b><span>{t.ready}</span></div><img src={asset("/dashboard/core.png")} alt="Panel de Own Terra"/></div></div><div className="caseGrid">{t.cards.map(([a,b])=><article key={a}><span>OWN TERRA</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
      <section className="section shell demoSection"><header><small>{t.demoTag}</small><h2>{t.demoTitle}</h2><p>{t.demoBody}</p></header><div className="demoFrame"><div className="demoBar"><span>SAFE PORTS · PRODUCT FILM</span><i>00:10</i></div><video controls autoPlay muted loop playsInline preload="metadata" poster={asset("/videos/own-terra-demo-poster.jpg")} aria-label={t.demoTitle}><source src={asset("/videos/own-terra-demo.mp4")} type="video/mp4"/></video></div><p className="demoHint">{t.demoHint}</p></section>
      <section className="section shell ownTerraGateway"><div><small>{t.discoverTag}</small><h2>{t.discoverTitle}</h2><p>{t.discoverBody}</p></div><a className="button primary" href="https://dev.own-terra.com/ecosistema" target="_blank" rel="noreferrer">{t.discoverCta}<ArrowRight/></a></section>
      <section className="section shell clientAccess" id="client-access"><div className="accessVisual"><div className="accessShield"><ShieldCheck/></div><span>SAFE PORTS · OWN TERRA</span><img src={asset("/dashboard/core.png")} alt="Portal operativo de Own Terra"/></div><div className="accessCopy"><small>{t.accessTag}</small><h2>{t.accessTitle}</h2><p>{t.accessBody}</p><div className="secureNote"><ShieldCheck/>{t.accessSecure}</div>{ownTerraUrl?<a className="button primary accessButton" href={ownTerraUrl} target="_blank" rel="noreferrer">{t.access}<LogIn/></a>:<span className="button accessDisabled" aria-disabled="true">{t.accessPending}</span>}<a className="accessHelp" href="mailto:safeports.contacto@gmail.com">{t.accessHelp} <ArrowRight/></a></div></section>
      <section className="section shell" id="principles"><div className="principle"><header><small>{t.why}</small><h2>{t.whyTitle}</h2></header><div className="principleGrid">{t.principles.map(([n,a,b])=><article key={n}><span>{n}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
      <section className="section shell contact" id="contact"><div><small>{t.contact}</small><h2>{t.contactTitle}</h2><p>{t.contactBody}</p><a href="mailto:safeports.contacto@gmail.com">safeports.contacto@gmail.com</a><span>México · United States</span></div><form onSubmit={submit}><div className="fieldRow"><label>{t.labels[0]}<input required name="name" autoComplete="name"/></label><label>{t.labels[1]}<input name="company" autoComplete="organization"/></label></div><label>{t.labels[2]}<input required type="email" name="email" autoComplete="email"/></label><label>{t.labels[3]}<textarea required name="message" rows="5"/></label><button className="button primary">{t.send}<ArrowRight/></button></form></section>
    </main><footer><Brand/><span>© 2026</span><p>{t.footer}</p></footer>
  </div>
}
